In [1]:
import numpy as np
import pandas as pd

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data = pd.DataFrame([[1, 6.5, 3], [1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3]])
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan

df.dropna(thresh=2)

          0         1         2
2 -0.248262       NaN -0.918902
3 -0.747305       NaN  1.021062
4 -0.000639 -0.361132  0.554204
5  2.572777  1.780399 -0.498926
6  0.244531  0.002245 -0.766847

In [19]:
df.fillna(0)

          0         1         2
0 -0.775679  0.000000  0.000000
1 -0.625841  0.000000  0.000000
2 -0.248262  0.000000 -0.918902
3 -0.747305  0.000000  1.021062
4 -0.000639 -0.361132  0.554204
5  2.572777  1.780399 -0.498926
6  0.244531  0.002245 -0.766847

In [23]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], 
                     "k2": [1,1,2,3,3,4,4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [25]:
data.duplicated()
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [26]:
data = pd.DataFrame({"food": ["bacon", "pulled_pork", "bacon", "pastrami", "corned beef", "bacon", "pastrami", "honey ham", "nova lox"], 
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled_pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [27]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [29]:
data["animal"] = data["food"].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled_pork     3.0     NaN
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [30]:
data = pd.Series([1, -999, 2, -999, -1000, 3])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [33]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [35]:
data.replace([-999, -1000], [np.nan, 2000])

0       1.0
1       NaN
2       2.0
3       NaN
4    2000.0
5       3.0
dtype: float64

In [36]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [38]:
def transform(x):
    return x[:3].upper()

data.index.map(transform)

Index(['OHI', 'COL', 'NEW'], dtype='str')

In [39]:
data.rename(index=str.title, columns=str.upper)

          ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [40]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [46]:
bins = [18, 25, 35, 60, 100]

age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [48]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [49]:
data = np.random.uniform(size=20)

pd.cut(data, 4, precision=2)

[(0.4, 0.58], (0.76, 0.94], (0.58, 0.76], (0.22, 0.4], (0.76, 0.94], ..., (0.58, 0.76], (0.4, 0.58], (0.58, 0.76], (0.22, 0.4], (0.58, 0.76]]
Length: 20
Categories (4, interval[float64, right]): [(0.22, 0.4] < (0.4, 0.58] < (0.58, 0.76] < (0.76, 0.94]]

In [51]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.016016     0.007965    -0.011370     0.037391
std       1.030543     1.008899     1.004394     1.023852
min      -2.938437    -3.311880    -2.832487    -3.035756
25%      -0.719419    -0.669509    -0.699348    -0.665579
50%      -0.040552     0.012003    -0.042192     0.030165
75%       0.693732     0.650588     0.716318     0.781376
max       3.240417     3.007027     3.400324     3.400938

In [52]:
col = data[2]
col[col.abs() > 3]

7      3.007214
522    3.400324
Name: 2, dtype: float64

In [56]:
col[col.abs() <= 3]

0      0.491192
1      0.401795
2     -1.537590
3     -1.366202
4      0.102306
         ...
995   -1.765295
996    0.507168
997    0.404945
998   -1.092387
999   -0.849501
Name: 2, Length: 998, dtype: float64

In [ ]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5,7)))

df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [70]:
sampler = np.random.permutation(5)
sampler

array([0, 1, 4, 3, 2])

In [71]:
df.iloc[sampler]

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [74]:
df.sample(n=3)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27

In [87]:
choices = pd.Series([5, 7, -1, 6, 4])

choices.sample(n=10, replace=1)

3    6
1    7
0    5
4    4
3    6
0    5
2   -1
0    5
0    5
3    6
dtype: int64

In [90]:
df = pd.DataFrame({"key": ['b', 'b', 'a', 'c', 'a', 'b'], 
                   "data1": range(6)})
print(df)

pd.get_dummies(df["key"], dtype=float)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

     a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [93]:
data = pd.Series({"Dave": "dave@google.com", "Steve": "steve@gmail.com",
          "Rob": "rob@gmail.com", "Wes": np.nan})
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: str

In [94]:
data.str.contains("@gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool